### ISSUE TITLE
`if` spelled as `iff`

### ISSUE THREAD

**Issue by XVilka** [triska/the-power-of-prolog#16]
In logical purity section:
```
call(Goal) is pure iff Goal is pure
```

![image](https://user-images.githubusercontent.com/203261/62863105-6e6e8380-bd3a-11e9-83c4-552aae7f675b.png)

**Comment by fnogatz** [comment]
Here, *iff* probably is short for *if and only if*, as it is [common](https://en.wikipedia.org/wiki/If_and_only_if) for logical formulae :)

**Comment by triska** [comment]
Yes indeed, it stands for *if and only if*, and this should be explained somewhere, maybe together with other terms.
