### ISSUE TITLE
Error in chapter on web applications 

### ISSUE THREAD

**Issue by cmsmcq** [triska/the-power-of-prolog#26]
The chapter on web applications [1] says, among other things

> In Scryer Prolog, library(xpath) allows us to access HTML elements by XPath specifications in a straight-forward way. 

[1] https://www.metalevel.at/prolog/web

But the example shown (`//li(text)`) is not an XPath expression.  It would be more accurate to describe the library as is done in the SWI Prolog documentation [2], as using "descriptions inspired by the XPath language".  Saying the expressions are XPath, when it is obvious at a glance that they are not, gives a bad impression, at least to some readers.

[2] https://www.swi-prolog.org/pldoc/man?section=xpath

**Comment by triska** [comment]
This is a valid criticism. I have installed 00b4302f37cc53ba1b76537ef940ef9ae15c5c31 to address it, could you please take a look?

Thank you a lot for reporting this!

**Comment by cmsmcq** [comment]
The change seems to resolve my issue; thanks!.  Closing.
