### ISSUE TITLE
Your length rule doesn't work for me

### ISSUE THREAD

**Issue by p4ulor** [triska/the-power-of-prolog#32]
In your website, your rule [list_length](https://www.metalevel.at/prolog/facets#:~:text=list_length(%5B%5D%2C%200).%0Alist_length(%5B_%7CLs%5D%2C%20N)%20%3A%2D%0A%20%20%20%20%20%20%20%20N%20%23%3E%200%2C%0A%20%20%20%20%20%20%20%20N%20%23%3D%20N0%20%2B%201%2C%0A%20%20%20%20%20%20%20%20list_length(Ls%2C%20N0).) gives me error **Syntax error: Operator expected**

![image](https://user-images.githubusercontent.com/32241574/160430994-05908d49-f1d7-4709-8478-3e080f8cadc7.png)
I'm a big noob at prolog, please bare with me

**Comment by GeoffChurch** [comment]
In SWI Prolog, you have to explicitly import the `clpfd` library, which exports `#>` and friends:
```prolog
:- use_module(library(clpfd)).
```
