### ISSUE TITLE
"Testing Prolog Programs": A new URL needed to the paper Concolic Testing in Logic Programming

### ISSUE THREAD

**Issue by haijinSk** [triska/the-power-of-prolog#47]
It seems that the target website (Universitat Politècnica de València) changed (structure of some) URLs; so in [Testing Prolog Programs](https://www.metalevel.at/prolog/testing) ("Further reading"), the link to the paper "Concolic Testing in Logic Programming" needs a new/edited URL.

Staying on the university website, this URL now works:

https://personales.upv.es/gvidal/german/iclp15/paper_CORR.pdf

**Comment by triska** [comment]
Thank you a lot, I updated the link!

**Comment by haijinSk** [comment]
I thank you; The Power of Prolog: the teleportation machine to the fascinating (and useful) world of a modern Prolog.
